[theme]
primaryColor = "#FF4B4B"
backgroundColor = "#FFFFFF"
secondaryBackgroundColor = "#F0F2F6"
textColor = "#262730"
font = "sans serif"

[server]
maxUploadSize = 200

[browser]
gatherUsageStats = false

[global]
developmentMode = false

[client]
showErrorDetails = true

[logger]
level = "info"
